# Generated by Django 2.2.1 on 2019-06-03 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
