# Generated by Django 2.2.1 on 2019-06-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0003_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.CharField(max_length=1000),
        ),
    ]
